services:
  news-bot:
    container_name: news-bot
    image: python:3.11-slim
    working_dir: /app
    env_file: .env
    environment:
      TZ: ${LOCAL_TZ:-Asia/Shanghai}
      LOCAL_TZ: ${LOCAL_TZ:-Asia/Shanghai}
      PYTHONUNBUFFERED: "1"
      LOG_LEVEL: ${LOG_LEVEL:-INFO}   # DEBUG/INFO/WARNING/ERROR
      LOG_JSON: ${LOG_JSON:-0}        # 1=JSON行日志
    volumes:
      - ./news_bot.py:/app/news_bot.py:ro
      - ./data:/app/data
      - ./.env:/app/.env:ro
    command: >
      sh -lc "pip install -U requests feedparser beautifulsoup4 python-dateutil python-dotenv
      pymysql deep-translator && python -u /app/news_bot.py"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import os,urllib.request,sys;u='https://api.telegram.org/bot'+os.getenv('BOT_TOKEN','')+'/getMe';sys.exit(0) if urllib.request.urlopen(u,timeout=6).read() else sys.exit(1)"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
